#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize

# class recurring_job
# include ScheduledJob
 
# run_every 18.hours
 
#   def perform
#     puts "perform job"
#   end
# end