require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DomainurlsController do

  # This should return the minimal set of attributes required to create a valid
  # Domainurl. As you add validations to Domainurl, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DomainurlsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all domainurls as @domainurls" do
      domainurl = Domainurl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:domainurls).should eq([domainurl])
    end
  end

  describe "GET show" do
    it "assigns the requested domainurl as @domainurl" do
      domainurl = Domainurl.create! valid_attributes
      get :show, {:id => domainurl.to_param}, valid_session
      assigns(:domainurl).should eq(domainurl)
    end
  end

  describe "GET new" do
    it "assigns a new domainurl as @domainurl" do
      get :new, {}, valid_session
      assigns(:domainurl).should be_a_new(Domainurl)
    end
  end

  describe "GET edit" do
    it "assigns the requested domainurl as @domainurl" do
      domainurl = Domainurl.create! valid_attributes
      get :edit, {:id => domainurl.to_param}, valid_session
      assigns(:domainurl).should eq(domainurl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Domainurl" do
        expect {
          post :create, {:domainurl => valid_attributes}, valid_session
        }.to change(Domainurl, :count).by(1)
      end

      it "assigns a newly created domainurl as @domainurl" do
        post :create, {:domainurl => valid_attributes}, valid_session
        assigns(:domainurl).should be_a(Domainurl)
        assigns(:domainurl).should be_persisted
      end

      it "redirects to the created domainurl" do
        post :create, {:domainurl => valid_attributes}, valid_session
        response.should redirect_to(Domainurl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved domainurl as @domainurl" do
        # Trigger the behavior that occurs when invalid params are submitted
        Domainurl.any_instance.stub(:save).and_return(false)
        post :create, {:domainurl => { "user_id" => "invalid value" }}, valid_session
        assigns(:domainurl).should be_a_new(Domainurl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Domainurl.any_instance.stub(:save).and_return(false)
        post :create, {:domainurl => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested domainurl" do
        domainurl = Domainurl.create! valid_attributes
        # Assuming there are no other domainurls in the database, this
        # specifies that the Domainurl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Domainurl.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => domainurl.to_param, :domainurl => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested domainurl as @domainurl" do
        domainurl = Domainurl.create! valid_attributes
        put :update, {:id => domainurl.to_param, :domainurl => valid_attributes}, valid_session
        assigns(:domainurl).should eq(domainurl)
      end

      it "redirects to the domainurl" do
        domainurl = Domainurl.create! valid_attributes
        put :update, {:id => domainurl.to_param, :domainurl => valid_attributes}, valid_session
        response.should redirect_to(domainurl)
      end
    end

    describe "with invalid params" do
      it "assigns the domainurl as @domainurl" do
        domainurl = Domainurl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Domainurl.any_instance.stub(:save).and_return(false)
        put :update, {:id => domainurl.to_param, :domainurl => { "user_id" => "invalid value" }}, valid_session
        assigns(:domainurl).should eq(domainurl)
      end

      it "re-renders the 'edit' template" do
        domainurl = Domainurl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Domainurl.any_instance.stub(:save).and_return(false)
        put :update, {:id => domainurl.to_param, :domainurl => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested domainurl" do
      domainurl = Domainurl.create! valid_attributes
      expect {
        delete :destroy, {:id => domainurl.to_param}, valid_session
      }.to change(Domainurl, :count).by(-1)
    end

    it "redirects to the domainurls list" do
      domainurl = Domainurl.create! valid_attributes
      delete :destroy, {:id => domainurl.to_param}, valid_session
      response.should redirect_to(domainurls_url)
    end
  end

end
